//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WorldHistoryBookStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Request2
    {
        
        public string ord_num { get; set; }
        public string stor_name { get; set; }
        public string title { get; set; }

    }
}