//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldHistoryBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class titleview
    {
        public string title { get; set; }
        public Nullable<byte> au_ord { get; set; }
        public string au_lname { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> ytd_sales { get; set; }
        public string pub_id { get; set; }
    }
}
